# Generated by Django 3.1.1 on 2020-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postApp', '0003_auto_20201223_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=10)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
